### ISSUE TITLE
A lot of errors after update to 2.5.0

### ISSUE THREAD

**Issue by uniqby** [apphud/ApphudSDK#66]
The application is not buildable after updating to version 2.5.0 via SPM.
There are no such problems with version 2.4.4.
Xcode Version 13.2.1 (13C100)

<img width="1766" alt="Screen Shot 2022-01-04 at 16 25 23" src="https://user-images.githubusercontent.com/1488394/148066036-2e7fbb2e-d061-4ba6-85ee-5cc5d8ea84f8.png">

**Comment by fury21** [comment]
Same problem to version 2.5.0 via SPM

**Comment by ren6** [comment]
Fixed in 2.5.2.

**Comment by uniqby** [comment]
Thank you! Now it' okay on iOS, but still not builds on macOS
My deployment target for macOS is 11.0

<img width="383" alt="Screen Shot 2022-01-08 at 16 53 51" src="https://user-images.githubusercontent.com/1488394/148646852-7a6d874c-45da-425e-aa93-21829c0f6e68.png">

**Comment by vlr-code** [comment]
Fixed in 2.5.3. for macOS
